steps:
- name: docker
  args: ['build','-t','gcr.io/$PROJECT_ID/mistrm','.']
- name: push
  args: ['push','gcr.io/$PROJECT_ID/mistrm']
- name: deploy
  args:
  - run
  - --filename=/k8s/depl.yaml
  - --image=gcr.io/$PROJECT_ID/mistrm
  - --location=us-east1
  - --cluster=mistrm
  - --namespace=restapi
images:
- 'gcr.io/$PROJECT_ID/mistrm'
options:
  logging: CLOUD_LOGGING_ONLY
