steps:
- name: docker
  args: ['build','-t','gcr.io/$PROJECT_ID/mistrm','.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push','gcr.io/$PROJECT_ID/mistrm']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/k8s/depl.yaml
  - --location=us-east1
  - --cluster=mistrm
images:
- 'gcr.io/$PROJECT_ID/mistrm'
options:
  logging: CLOUD_LOGGING_ONLY
